-- ============================================================
-- Migration: 20260713000002_create_cases_table
-- Purpose:   Core case table. No user account foreign key by design.
--            Access is gated by case_code + optional PIN, validated
--            server-side via the verify_case_access() function in a
--            later migration.
-- ============================================================

CREATE TABLE cases (
  -- Primary key
  case_id       UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Human-readable, URL-safe case code e.g. "SW-7X9K2M"
  -- Generated by the application layer before insert.
  case_code     TEXT          NOT NULL UNIQUE,

  -- bcrypt / argon2id hash of the optional user-set PIN.
  -- NULL means no PIN is set for this case.
  -- NEVER store the plain PIN — only ever store the hash.
  pin_hash      TEXT          DEFAULT NULL,

  -- Case lifecycle state
  status        case_status   NOT NULL DEFAULT 'draft',

  created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);

-- Fast lookup by case_code (used on every access check)
CREATE INDEX idx_cases_case_code ON cases (case_code);

-- Automatically update updated_at on every row change
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trg_cases_updated_at
  BEFORE UPDATE ON cases
  FOR EACH ROW EXECUTE PROCEDURE set_updated_at();

-- ── Row Level Security ─────────────────────────────────────────────────────
-- RLS is ENABLED. No policy grants direct SELECT/INSERT/UPDATE/DELETE to
-- anon or authenticated roles based on JWT claims — there are no user
-- accounts. All data access goes through server-side API routes that call
-- verify_case_access() (defined in migration 000004) and use the service
-- role key, which bypasses RLS. The policies below lock out every other
-- direct client path.

ALTER TABLE cases ENABLE ROW LEVEL SECURITY;

-- Deny all direct client access. Only the service role (server-side API)
-- may read or modify cases.
CREATE POLICY "cases_deny_all_direct_client_access"
  ON cases
  FOR ALL
  TO anon, authenticated
  USING (false)
  WITH CHECK (false);
